name: CustomKitPvP
version: '${project.version}'
main: de.mxchy.customkitpvp.CustomKitPvP
api-version: '1.20'
commands:
  setarena:
    description: this command sets the coordinates of the PvP arena
    permission: kitpvp.setarena
  addnewkit:
    description: this command opens the kit creation menu
    permission: kitpvp.addnewkit
  deletekit:
    description: this command opens the kit deletion menu
    permission: kitpvp.deletekit
  selectkit:
    description: this command opens the kit selection menu

