name: CustomKitPvP
version: '1.0-SNAPSHOT'
main: de.mxchy.customkitpvp.CustomKitPvP
api-version: '1.20'
commands:
  setarena:
    description: this command sets the coordinates of the PvP arena
    permission: kitpvp.managekit
  addnewkit:
    description: this command opens the kit creation menu
    permission: kitpvp.managekit
  deletekit:
    description: this command opens the kit deletion menu
    permission: kitpvp.managekit
  selectkit:
    description: this command opens the kit selection menu

